before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

rspec:
  script:
    - RAILS_ENV=test bundle exec rspec

jasmine:
  script:
    - bundle exec rake jasmine:ci
