User.create([{ username: 'User',
                      email: 'user@gmail.com',
                      password: 'qwerty',
                      password_confirmation:'qwerty' },
                      { username: 'User2',
                      email: 'user2@gmail.com',
                      password: 'qwerty',
                      password_confirmation:'qwerty' },
                      { username: 'User3',
                      email: 'user3@gmail.com',
                      password: 'qwerty',
                      password_confirmation:'qwerty' }])

Task.create([{ name: 'Task1',
                      description: 'Task №1',
                      status: '1',
                      priority:'1' },
                      { name: 'Task2',
                      description: 'Task №2',
                      status: '2',
                      priority:'2' },
                      { name: 'Task3',
                      description: 'Task №3',
                      status: '3',
                      priority:'3' }])
