User.create([{ username: 'User',
                      email: 'user@gmail.com',
                      first_name:'First',
                      last_name:'User',
                      password:'qwerty',
                      password_confirmation:'qwerty' },
                      { username: 'User2',
                      email: 'user2@gmail.com',
                      first_name:'Second',
                      last_name:'User',
                      password:'qwerty',
                      password_confirmation:'qwerty' },
                      { username: 'User3',
                      email: 'user3@gmail.com',
                      first_name:'First',
                      last_name:'User',
                      password: 'qwerty',
                      password_confirmation:'qwerty' }])

Task.create([{ name: 'Task1',
                      description: 'Task №1',
                      status: '1' },
                      { name: 'Task2',
                      description: 'Task №2',
                      status: '2' },
                      { name: 'Task3',
                      description: 'Task №3',
                      status: '3' }])

Priority.create([{ user_id: nil,
                      name: 'High',
                      value: 999,
                      color: '#ff0000' },
                      { user_id: nil,
                      name: 'Medium',
                      value: 500,
                      color: '#0000ff' },
                      { user_id: nil,
                      name: 'Low',
                      value: 100,
                      color: '#00ff00' }])
